Comment out Slack Notification

diff --git a/.github/workflows/slack-notification.yml b/.github/workflows/slack-notification.yml
--- a/.github/workflows/slack-notification.yml
+++ b/.github/workflows/slack-notification.yml
@@ -1,44 +1,44 @@
-name: Slack Notification Test
+# name: Slack Notification Test
 
-on:
-  push:
-    branches:
-      - main
+# on:
+#   push:
+#     branches:
+#       - main
 
-jobs:
-  test-slack-notification:
-    name: Test Slack Notification
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
+# jobs:
+#   test-slack-notification:
+#     name: Test Slack Notification
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Checkout
+#         uses: actions/checkout@v4
 
-      - name: Extract PR number from commit message
-        id: extract_pr
-        run: |
-          PR_NUMBER=$(git log -1 --pretty=%B | grep -oP 'Merge pull request #\K\d+')
-          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
-          echo "::set-output name=pr_number::$PR_NUMBER"
+#       - name: Extract PR number from commit message
+#         id: extract_pr
+#         run: |
+#           PR_NUMBER=$(git log -1 --pretty=%B | grep -oP 'Merge pull request #\K\d+')
+#           echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
+#           echo "::set-output name=pr_number::$PR_NUMBER"
 
-      - name: Force Failure
-        id: force_failure
-        run: |
-          echo "This step will fail"
-          exit 1
+#       - name: Force Failure
+#         id: force_failure
+#         run: |
+#           echo "This step will fail"
+#           exit 1
 
-      - name: Notify Slack on Failure
-        if: failure()
-        id: slack_notification
-        uses: slackapi/slack-github-action@70cd7be8e40a46e8b0eced40b0de447bdb42f68e # v1.26.0
-        with:
-          payload: |
-            {
-              "run_id": "${{ github.run_id }}",
-              "pull_request": "${{ github.event.pull_request.html_url }}",
-              "event_number": "${{ github.event.number }}",
-              "ref": "${{ github.ref }}",
-              "pr_number": "${{ steps.extract_pr.outputs.pr_number }}"
-            }
-        env:
-          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
-          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
+#       - name: Notify Slack on Failure
+#         if: failure()
+#         id: slack_notification
+#         uses: slackapi/slack-github-action@70cd7be8e40a46e8b0eced40b0de447bdb42f68e # v1.26.0
+#         with:
+#           payload: |
+#             {
+#               "run_id": "${{ github.run_id }}",
+#               "pull_request": "${{ github.event.pull_request.html_url }}",
+#               "event_number": "${{ github.event.number }}",
+#               "ref": "${{ github.ref }}",
+#               "pr_number": "${{ steps.extract_pr.outputs.pr_number }}"
+#             }
+#         env:
+#           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+#           SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
